
function Inicio(){$('#detalleempleoopen').hide();$('#detallePubli').hide();$('#listpostulantes').hide();$('#detalleempresas').hide();$('#verPostulante').hide()}
Inicio();var dateTable;$(document).ready(function(){$('#verempleo').dataTable({"aProcessing":!0,"aServerSide":!0,"language":{"url":"//cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json",},"ajax":{"url":"ajax/PublicacionesEmpresa.ajax.php","dataSrc":""},"columns":[{"data":"editar"},{"data":"puesto"},{"data":"detalle"},{"data":"postulante"},{"data":"optione"}],"responsive":"true","bDestroy":!0,"iDisplayLength":10,"order":[[0,"desc"]]})});$('#verempleo').DataTable();function openModalpostulados(){$('#listempleos').hide();$('#listpostulantes').show()}
function regresarVerempleodPostulados(){$('#listempleos').show();$('#listpostulantes').hide()}
function postulados(id){openModalpostulados();var idpubli=id;$('#listpostulados').dataTable({"aProcessing":!0,"aServerSide":!0,"language":{"url":"//cdn.datatables.net/plug-ins/1.10.24/i18n/Spanish.json",},"ajax":{"url":"ajax/postulados.ajax.php",'data':{'idPostu':idpubli},'type':'post',"dataSrc":""},"columns":[{"data":"nombre"},{"data":"apellido"},{render:function(data,type,row){return'<div class="text-center"><button class="btn btn-primary btn-sm mt-1 ml-1" title="Ver Perfil" onclick="verPerfilPostulante('+row[2]+','+row[1]+')">Ver Perfil</button></div>'}}],"responsive":"true","bDestroy":!0,"iDisplayLength":10,"order":[[0,"desc"]]});$('#listpostulados').DataTable()}
function openModalVerPostulantes(){$('#listpostulantes').hide();$('#verPostulante').show()}
function regresarVerPostulados(){$('#listpostulantes').show();$('#verPostulante').hide()}
function verPerfilPostulante(id,idpubli){openModalVerPostulantes();const nombre=document.querySelector('.nombre-postulante');const apellido=document.querySelector('.apellido-postulante');const email=document.querySelector('.email-postulante');const carnet=document.querySelector('.carnet-postulante');const tel=document.querySelector('.tel-postulante');const localidad=document.querySelector('.localidad-postulante');const direccion=document.querySelector('.direccion-postulante');const sobreMi=document.querySelector('.sobreMi-postulante');const foto=document.querySelector('.foto-postulante');const genero=document.querySelector('.genero-postulante');const estado=document.querySelector('.Estado-postulante');const discapacidad=document.querySelector('.Discapacidad-postulante');const linkedin=document.querySelector('.Linkedin-postulante');const fecha=document.querySelector('.Fecha-postulante');const habilidadC=document.querySelector('.habilidad-postulacion');const idiomaC=document.querySelector('.idioma-postulacion');const laboralC=document.querySelector('.laboral-postulacion');const educacionC=document.querySelector('.educacion-postulacion');const miCv=document.querySelector('#miCv');nombre.textContent='';apellido.textContent='';email.textContent='';carnet.textContent='';tel.textContent='';localidad.textContent='';sobreMi.textContent='';foto.src='';genero.textContent='Genero - ';estado.textContent='Estado Civil -';discapacidad.textContent='Discapacidad -';linkedin.textContent='Linkedin -';fecha.textContent='Fecha de Nacimiento -';habilidadC.innerHTML='';idiomaC.innerHTML='';laboralC.innerHTML='';educacionC.innerHTML='';miCv.href='#';$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante1="+id,success:function(response){let json=JSON.parse(response);json.forEach(json=>{nombre.textContent=json.nombre;apellido.textContent=json.apellido;email.textContent=json.correo;carnet.textContent=json.num_carnet;tel.textContent=json.celular+' - '+json.telefono;localidad.textContent=json.departamento+' - '+json.provincia+' - '+json.distrito;direccion.textContent=json.direccion;sobreMi.textContent=json.sobre_mi;miCv.href=json.cv
if(json.genero==1){genero.textContent='Genero - Masculino'}else if(json.genero==2){genero.textContent='Genero - Femenino'}else{genero.textContent='Genero - Otro'}
if(json.estado_civil==1){estado.textContent='Estado Civil - Soltero(a)'}else if(json.estado_civil==2){estado.textContent='Estado Civil - Casado(a)'}else if(json.estado_civil==3){estado.textContent='Estado Civil - Divorciado(a)'}else if(json.estado_civil==4){estado.textContent='Estado Civil - Viudo(a)'}else{estado.textContent='Estado Civil - Conviviente'}
if(json.discapacidad=='si'){discapacidad.textContent='Discapacidad - Si'}else{discapacidad.discapacidad='Discapacidad - No'}
linkedin.textContent='Linkedin - '+json.linkendin;fecha.textContent='Fecha de Nacimiento - '+json.fecha_nac;foto.src=json.foto_perfil})}});$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante2="+id,success:function(response){let habilidad=JSON.parse(response);habilidad.forEach(json=>{const li=document.createElement('li');li.innerHTML=`<i class="far fa-star mr-3 mb-3"></i> ${json.nconocimiento}`
habilidadC.appendChild(li)})}});$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante3="+id,success:function(response){let idioma=JSON.parse(response);idioma.forEach(json=>{const li=document.createElement('li');li.innerHTML=`<i class="fas fa-language mr-3 mb-3"></i> ${json.nidioma} - ${(json.nnivel[0]).toUpperCase() + (json.nnivel).slice(1)}`
idiomaC.appendChild(li)})}});$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante4="+id,success:function(response){let laboral=JSON.parse(response);laboral.forEach(json=>{const div1=document.createElement('div');const div2=document.createElement('div');const div3=document.createElement('div');div1.classList.add('row','mb-3');div2.classList.add('col-12','col-md-3');div3.classList.add('col-12','col-md-9');div2.textContent=`${json.fecha_ini} - ${json.fecah_fin}`;div3.innerHTML=`
                    <span><b>Empresa :</b> ${json.empresa}</span>
                    <br>
                    <span><b>Cargo :</b> ${json.tipo_cargo}</span>
                `;div1.appendChild(div2);div1.appendChild(div3);laboralC.appendChild(div1)})}});$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante5="+id,success:function(response){let educacion=JSON.parse(response);educacion.forEach(json=>{const div1=document.createElement('div');const div2=document.createElement('div');const div3=document.createElement('div');div1.classList.add('row','mb-3');div2.classList.add('col-12','col-md-3');div3.classList.add('col-12','col-md-9');div2.textContent=`${json.fecha_ini} - ${json.fecah_fin}`;div3.innerHTML=`
                    <span><b>Instituci¨®n :</b> ${json.centro_educacion}</span>
                    <br>
                    <span><b>Area de estudio :</b> ${json.tipo_area_estudio}</span>
                    <br>
                    <span><b>Tipo de estudio :</b> ${json.nivel}</span>
                    <br>
                    <span><b>Estado :</b> ${json.estado}</span>
                `;div1.appendChild(div2);div1.appendChild(div3);educacionC.appendChild(div1)})}});$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"idPostulante6="+idpubli+"&id="+id,success:function(response){let veri=JSON.parse(response);console.log(veri.estado_postulacion);if(veri.estado_postulacion=='P'){document.querySelector('#Postulada1').checked=!0}else if(veri.estado_postulacion=='V'){document.querySelector('#Visto2').checked=!0}else if(veri.estado_postulacion=='G'){document.querySelector('#Gestion3').checked=!0}else if(veri.estado_postulacion=='F'){document.querySelector('#Finalista4').checked=!0}
$('#idpostulacion').val(veri.id_postulacion)}})}
function editarPublicacion(id){var idpubli=id;$.ajax({url:'ajax/EditarPublicacion.ajax.php',type:'POST',data:{idpubli:idpubli},dataType:'json',success:function(data){$("#ideditPubli").val(data.id_publicaciones);$("#editpuesto").val(data.puesto);$("#editselectDepartamento").val(data.departamento);$("#editselectProvincia").val(data.provincia);$("#editselectDistrito").val(data.distrito);$("#editdireccion").val(data.direccion);$("#editcontrato").val(data.contrato);$("#editespecialidad").val(data.especialidad);$("#editexperiencia").val(data.experiencia);$("#editsalario").val(data.salario);$("#editoptradio").val(data.trb_remoto);$("#editdescripcion").val(data.descripcion)},fail:function(data){alert('error')}})}
function openModalDetalle(){$('#listempleos').hide();$('#detallePubli').show()}
function regresarVerempleo(){$('#listempleos').show();$('#detallePubli').hide()}
function detallePublicacion(id){openModalDetalle();var idpubli=id;$.ajax({url:'ajax/EditarPublicacion.ajax.php',type:'POST',data:{idpubli:idpubli},dataType:'json',success:function(data){console.log(data);$("#iddetalleEmpresa").val(data.id_publicaciones);$("#detpuesto").text(data.puesto);$("#detdepartamento").text(data.departamento);$("#detprovincia").text(data.provincia);$("#detdistrito").text(data.distrito);$("#detdireccion").text(data.direccion);$("#detcontrato").text(data.contrato);$("#detespecialidad").text(data.tipo_area_estudio);$("#detexperiencia").text(data.experiencia);$("#detsalario").text(data.salario);$("#detremoto").text(data.trb_remoto);$("#detdescripcion").text(data.descripcion);$("#detfecha").text(data.fecha);$("#dethora").text(data.hora)},fail:function(data){alert('error')}})}
function openModalDetalleEmpleo(){$('#empleos').hide();$('#detalleempleoopen').show()}
function regresarEmpleos(){$('#empleos').show();$('#detalleempleoopen').hide()}
function detalleEmpleo(id){openModalDetalleEmpleo();var idpubli=id;$.ajax({url:'ajax/EditarPublicacion.ajax.php',type:'POST',data:{idpubli:idpubli},dataType:'json',success:function(data){$("#detempleid").val(data.id_publicaciones);$("#detemplepuesto").text(data.puesto);$("#detempledepartamento").text(data.departamento);$("#detempleprovincia").text(data.provincia);$("#detempledistrito").text(data.distrito);$("#detempledireccion").text(data.direccion);$("#detemplecontrato").text(data.contrato);$("#detempleespecialidad").text(data.especialidad);$("#detempleexperiencia").text(data.experiencia);$("#detemplesueldo").text(data.salario);$("#detempleremoto").text(data.trb_remoto);$("#detempledescripcion").text(data.descripcion);$("#detemplefecha").text(data.fecha);$("#detemplehora").text(data.hora)},fail:function(data){alert('error')}})}
function eliminarPublicacion(id){var parametros={'codi':id}
$.ajax({data:parametros,url:"ajax/PublicacionesEmpresa.ajax.php",type:"POST",success:function(){alert("eliminado");location.reload()}})}
function eliminarPostulante(id){var parametros={'codi':id}
$.ajax({data:parametros,url:"ajax/postulados.ajax.php",type:"POST",success:function(response){if(response=='Eliminado'){alert("eliminado");location.reload()}}})}
function openModalDetalleEmpresas(){$("#empleos").hide();$("#detalleempresas").show()}
function regresarEmpresas(){$("#empleos").show();$("#detalleempresas").hide()}
function detalleEmpresas(id){openModalDetalleEmpresas();var idempresa=id;$.ajax({url:"ajax/DetalleEmpresas.ajax.php",type:"POST",data:{idempresa:idempresa},dataType:"json",success:function(data){$("#DEidempresa").val(data.idempresa);if(data.nom_empresa!=null){$("#DEnom_empresa").text(data.nom_empresa)}else{$("#DEnom_empresa").text("Sin Especificar")}
if(data.ruc!=null){$("#DEruc").text(data.ruc)}else{$("#DEruc").text("Sin Especificar")}
if(data.rubro!=null){$("#DErubro").text(data.tipo_rubro)}else{$("#DErubro").text("Sin Especificar")}
if(data.razon_social!=null){$("#DErazon_social").text(data.razon_social)}else{$("#DErazon_social").text("Sin Especificar")}
if(data.industria!=null){$("#DEindustria").text(data.industria)}else{$("#DEindustria").text("Sin Especificar")}
if(data.logo!=null){$("#DElogo").attr("src",data.logo)}else{$("#DElogo").attr("src","vista/images/foto-por-defecto.png")}
if(data.foto_perfil!=null){$("#DEfotoPerfil").attr("src",data.foto_perfil)}else{$("#DEfotoPerfil").attr("src","vista/images/foto-por-defecto.png")}
if(data.mision_vision!=null){$("#DEmision_vision").text(data.mision_vision)}else{$("#DEmision_vision").text("Sin Especificar")}
if(data.beneficios!=null){$("#DEbeneficios").text(data.beneficios)}else{$("#DEbeneficios").text("Sin Especificar")}
if(data.departamento!=null){$("#DEdepartamento").text(data.departamento)}else{$("#DEdepartamento").text("Sin Especificar")}
if(data.provincia!=null){$("#DEprovincia").text(data.provincia)}else{$("#DEprovincia").text("Sin Especificar")}
if(data.distrito!=null){$("#DEdistrito").text(data.distrito)}else{$("#DEdistrito").text("Sin Especificar")}
if(data.direccion!=null){$("#DEdireccion").text(data.direccion)}else{$("#DEdireccion").text("Sin Especificar")}},fail:function(data){alert("error")},})}
$("#formularioEstado").submit(function(e){e.preventDefault();const valorE=document.querySelector('input[type="radio"]:checked').value;const id=document.querySelector('#idpostulacion').value;$.ajax({type:"POST",url:"ajax/verPostulante.ajax.php",data:"estado="+valorE+"&id="+id,success:function(response){if(response=='ok'){alert('Estado Actualizado')}}})})


  

